/*
 * File: ActRectificadaCtaByLlave2Result.java  2008/10/09 10:09:44
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:r2bgh0fDzm6Bf6hSM-eGuY>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Output parameters of procedure "PKG_SII_RENTA_ME.ACT_RECTIFICADA_CTA_BY_LLAVE2".
 */
public class ActRectificadaCtaByLlave2Result implements Serializable
{
    private static final long serialVersionUID = 1L;
    private BigDecimal myExiste;
    private ProcedureTable[] myTables;

    /**
     * Constructor.
     */
    public ActRectificadaCtaByLlave2Result()
    {
    }

    /**
     * Returns the value of "Existe".
     */
    public BigDecimal getExiste()
    {
        return myExiste;
    }

    /**
     * Changes the value of "Existe".
     */
    public void setExiste(BigDecimal value)
    {
        myExiste = value;
    }

    /**
     * Returns the value of "ProcedureTables".
     */
    public ProcedureTable[] getProcedureTables()
    {
        return myTables;
    }

    /**
     * Changes the value of "ProcedureTables".
     */
    public void setProcedureTables(ProcedureTable[] value)
    {
        myTables = value;
    }
}
