/*
 * File: Formulario.java  2008/10/09 10:09:46
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:U-+y9q-fUkBGlypUlEuQ4j>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Implements the "FORMULARIO" user-defined object.
 */
public class Formulario implements Serializable
{
    private static final long serialVersionUID = 1L;

    // Fields of the user-defined object
    private BigDecimal  myIndcta;     // NUMBER
    private CtaCut      myCtaobj;     // CTA_CUT
    private MovCut      myMovobj;     // MOV_CUT
    private ItemCut[]   myItemscoll;  // ITEMS_CUT

    /**
     * Constructor.
     */
    public Formulario()
    {
    }

    /**
     * Gets the INDCTA value of this Formulario.
     */
    public BigDecimal getIndcta()
    {
        return myIndcta;
    }

    /**
     * Sets the INDCTA value of this Formulario.
     */
    public void setIndcta(BigDecimal value)
    {
        myIndcta = value;
    }

    /**
     * Gets the CTAOBJ value of this Formulario.
     */
    public CtaCut getCtaobj()
    {
        return myCtaobj;
    }

    /**
     * Sets the CTAOBJ value of this Formulario.
     */
    public void setCtaobj(CtaCut value)
    {
        myCtaobj = value;
    }

    /**
     * Gets the MOVOBJ value of this Formulario.
     */
    public MovCut getMovobj()
    {
        return myMovobj;
    }

    /**
     * Sets the MOVOBJ value of this Formulario.
     */
    public void setMovobj(MovCut value)
    {
        myMovobj = value;
    }

    /**
     * Gets the ITEMSCOLL value of this Formulario.
     */
    public ItemCut[] getItemscoll()
    {
        return myItemscoll;
    }

    /**
     * Sets the ITEMSCOLL value of this Formulario.
     */
    public void setItemscoll(ItemCut[] value)
    {
        myItemscoll = value;
    }
}
