/*
 * File: InsertItemsByCollCaller.java  2008/10/09 10:09:44
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:4zfg0+c+sF6HfSefdOCs-Z>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Types;
import java.util.ArrayList;

/**
 * Implements a caller of procedure "PKG_SII_RENTA_ME.INSERT_ITEMS_BY_COLL".
 */
public class InsertItemsByCollCaller extends ProcedureCaller
{
    /**
     * Executes procedure "PKG_SII_RENTA_ME.INSERT_ITEMS_BY_COLL".
     *
     * ITM_COL            ITEMS_CUT          Input
     * COD_OUT            NUMBER             Output
     */
    public static InsertItemsByCollResult execute(Connection conn, ItemCut[] itmCol)
        throws java.sql.SQLException
    {
        InsertItemsByCollResult result = new InsertItemsByCollResult();
        ArrayList resultSets = new ArrayList();
        CallableStatement call = conn.prepareCall("{call SII.PKG_SII_RENTA_ME.INSERT_ITEMS_BY_COLL(?,?)}");
        try
        {
            call.setObject(1, dbItemsCut(itmCol, conn));
            call.registerOutParameter(2, Types.NUMERIC);
            int updateCount = 0;
            boolean haveRset = call.execute();
            while (haveRset || updateCount != -1)
            {
                if (!haveRset)
                    updateCount = call.getUpdateCount();
                else
                    resultSets.add(toProcedureTable(call.getResultSet()));
                haveRset = call.getMoreResults();
            }
            result.setCodOut(call.getBigDecimal(2));
        }
        finally
        {
            call.close();
        }
        if (resultSets.size() > 0)
        {
            ProcedureTable[] tables = new ProcedureTable[resultSets.size()];
            result.setProcedureTables((ProcedureTable[]) resultSets.toArray(tables));
        }
        return result;
    }
}
