/*
 * File: InsertItemsByCollResult.java  2008/10/09 10:09:44
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:5rC9rywbN-Dm0Y01Fjf3Cn>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Output parameters of procedure "PKG_SII_RENTA_ME.INSERT_ITEMS_BY_COLL".
 */
public class InsertItemsByCollResult implements Serializable
{
    private static final long serialVersionUID = 1L;
    private BigDecimal myCodOut;
    private ProcedureTable[] myTables;

    /**
     * Constructor.
     */
    public InsertItemsByCollResult()
    {
    }

    /**
     * Returns the value of "CodOut".
     */
    public BigDecimal getCodOut()
    {
        return myCodOut;
    }

    /**
     * Changes the value of "CodOut".
     */
    public void setCodOut(BigDecimal value)
    {
        myCodOut = value;
    }

    /**
     * Returns the value of "ProcedureTables".
     */
    public ProcedureTable[] getProcedureTables()
    {
        return myTables;
    }

    /**
     * Changes the value of "ProcedureTables".
     */
    public void setProcedureTables(ProcedureTable[] value)
    {
        myTables = value;
    }
}
