/*
 * File: ItemCut.java  2008/10/09 10:09:46
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:rr8PAjpkxi5O+JqpY5+H3G>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Implements the "ITEM_CUT" user-defined object.
 */
public class ItemCut implements Serializable
{
    private static final long serialVersionUID = 1L;

    // Fields of the user-defined object
    private BigDecimal  myIdMov;     // NUMBER(12)
    private BigDecimal  myCodg;      // NUMBER(4)
    private String      myDatoType;  // CHAR(1)
    private BigDecimal  myStatus;    // NUMBER(1)
    private String      myValor;     // VARCHAR2(4000)

    /**
     * Constructor.
     */
    public ItemCut()
    {
    }

    /**
     * Gets the ID_MOV value of this ItemCut.
     */
    public BigDecimal getIdMov()
    {
        return myIdMov;
    }

    /**
     * Sets the ID_MOV value of this ItemCut.
     */
    public void setIdMov(BigDecimal value)
    {
        myIdMov = value;
    }

    /**
     * Gets the CODG value of this ItemCut.
     */
    public BigDecimal getCodg()
    {
        return myCodg;
    }

    /**
     * Sets the CODG value of this ItemCut.
     */
    public void setCodg(BigDecimal value)
    {
        myCodg = value;
    }

    /**
     * Gets the DATO_TYPE value of this ItemCut.
     */
    public String getDatoType()
    {
        return myDatoType;
    }

    /**
     * Sets the DATO_TYPE value of this ItemCut.
     */
    public void setDatoType(String value)
    {
        myDatoType = value;
    }

    /**
     * Gets the STATUS value of this ItemCut.
     */
    public BigDecimal getStatus()
    {
        return myStatus;
    }

    /**
     * Sets the STATUS value of this ItemCut.
     */
    public void setStatus(BigDecimal value)
    {
        myStatus = value;
    }

    /**
     * Gets the VALOR value of this ItemCut.
     */
    public String getValor()
    {
        return myValor;
    }

    /**
     * Sets the VALOR value of this ItemCut.
     */
    public void setValor(String value)
    {
        myValor = value;
    }
}
