/*
 * File: MovCut.java  2008/10/09 10:09:46
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:OuRFFjzLc0bC2hWZ-gwECc>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Implements the "MOV_CUT" user-defined object.
 */
public class MovCut implements Serializable
{
    private static final long serialVersionUID = 1L;

    // Fields of the user-defined object
    private BigDecimal  myCuenta;       // NUMBER
    private BigDecimal  myNumtrx;       // NUMBER
    private BigDecimal  myMovtipo;      // NUMBER
    private Date        myFecha;        // DATE
    private Date        myFechaVto;     // DATE
    private BigDecimal  myFormtipo;     // NUMBER
    private String      myFormver;      // CHAR(1)
    private BigDecimal  myFolio;        // NUMBER
    private BigDecimal  myMoneda;       // NUMBER
    private BigDecimal  myMonto;        // NUMBER
    private BigDecimal  myMontopesos;   // NUMBER
    private BigDecimal  myValorcambio;  // NUMBER
    private BigDecimal  myEstado;       // NUMBER
    private BigDecimal  myRutira;       // NUMBER
    private String      myDvira;        // VARCHAR2(2)
    private BigDecimal  myFol01;        // NUMBER
    private BigDecimal  myCod9927;      // NUMBER
    private BigDecimal  myMontoret;     // NUMBER
    private BigDecimal  myMontoimp;     // NUMBER
    private BigDecimal  myMontopag;     // NUMBER
    private Date        myPeriodocont;  // DATE

    /**
     * Constructor.
     */
    public MovCut()
    {
    }

    /**
     * Gets the CUENTA value of this MovCut.
     */
    public BigDecimal getCuenta()
    {
        return myCuenta;
    }

    /**
     * Sets the CUENTA value of this MovCut.
     */
    public void setCuenta(BigDecimal value)
    {
        myCuenta = value;
    }

    /**
     * Gets the NUMTRX value of this MovCut.
     */
    public BigDecimal getNumtrx()
    {
        return myNumtrx;
    }

    /**
     * Sets the NUMTRX value of this MovCut.
     */
    public void setNumtrx(BigDecimal value)
    {
        myNumtrx = value;
    }

    /**
     * Gets the MOVTIPO value of this MovCut.
     */
    public BigDecimal getMovtipo()
    {
        return myMovtipo;
    }

    /**
     * Sets the MOVTIPO value of this MovCut.
     */
    public void setMovtipo(BigDecimal value)
    {
        myMovtipo = value;
    }

    /**
     * Gets the FECHA value of this MovCut.
     */
    public Date getFecha()
    {
        return myFecha;
    }

    /**
     * Sets the FECHA value of this MovCut.
     */
    public void setFecha(Date value)
    {
        myFecha = value;
    }

    /**
     * Gets the FECHA_VTO value of this MovCut.
     */
    public Date getFechaVto()
    {
        return myFechaVto;
    }

    /**
     * Sets the FECHA_VTO value of this MovCut.
     */
    public void setFechaVto(Date value)
    {
        myFechaVto = value;
    }

    /**
     * Gets the FORMTIPO value of this MovCut.
     */
    public BigDecimal getFormtipo()
    {
        return myFormtipo;
    }

    /**
     * Sets the FORMTIPO value of this MovCut.
     */
    public void setFormtipo(BigDecimal value)
    {
        myFormtipo = value;
    }

    /**
     * Gets the FORMVER value of this MovCut.
     */
    public String getFormver()
    {
        return myFormver;
    }

    /**
     * Sets the FORMVER value of this MovCut.
     */
    public void setFormver(String value)
    {
        myFormver = value;
    }

    /**
     * Gets the FOLIO value of this MovCut.
     */
    public BigDecimal getFolio()
    {
        return myFolio;
    }

    /**
     * Sets the FOLIO value of this MovCut.
     */
    public void setFolio(BigDecimal value)
    {
        myFolio = value;
    }

    /**
     * Gets the MONEDA value of this MovCut.
     */
    public BigDecimal getMoneda()
    {
        return myMoneda;
    }

    /**
     * Sets the MONEDA value of this MovCut.
     */
    public void setMoneda(BigDecimal value)
    {
        myMoneda = value;
    }

    /**
     * Gets the MONTO value of this MovCut.
     */
    public BigDecimal getMonto()
    {
        return myMonto;
    }

    /**
     * Sets the MONTO value of this MovCut.
     */
    public void setMonto(BigDecimal value)
    {
        myMonto = value;
    }

    /**
     * Gets the MONTOPESOS value of this MovCut.
     */
    public BigDecimal getMontopesos()
    {
        return myMontopesos;
    }

    /**
     * Sets the MONTOPESOS value of this MovCut.
     */
    public void setMontopesos(BigDecimal value)
    {
        myMontopesos = value;
    }

    /**
     * Gets the VALORCAMBIO value of this MovCut.
     */
    public BigDecimal getValorcambio()
    {
        return myValorcambio;
    }

    /**
     * Sets the VALORCAMBIO value of this MovCut.
     */
    public void setValorcambio(BigDecimal value)
    {
        myValorcambio = value;
    }

    /**
     * Gets the ESTADO value of this MovCut.
     */
    public BigDecimal getEstado()
    {
        return myEstado;
    }

    /**
     * Sets the ESTADO value of this MovCut.
     */
    public void setEstado(BigDecimal value)
    {
        myEstado = value;
    }

    /**
     * Gets the RUTIRA value of this MovCut.
     */
    public BigDecimal getRutira()
    {
        return myRutira;
    }

    /**
     * Sets the RUTIRA value of this MovCut.
     */
    public void setRutira(BigDecimal value)
    {
        myRutira = value;
    }

    /**
     * Gets the DVIRA value of this MovCut.
     */
    public String getDvira()
    {
        return myDvira;
    }

    /**
     * Sets the DVIRA value of this MovCut.
     */
    public void setDvira(String value)
    {
        myDvira = value;
    }

    /**
     * Gets the FOL01 value of this MovCut.
     */
    public BigDecimal getFol01()
    {
        return myFol01;
    }

    /**
     * Sets the FOL01 value of this MovCut.
     */
    public void setFol01(BigDecimal value)
    {
        myFol01 = value;
    }

    /**
     * Gets the COD9927 value of this MovCut.
     */
    public BigDecimal getCod9927()
    {
        return myCod9927;
    }

    /**
     * Sets the COD9927 value of this MovCut.
     */
    public void setCod9927(BigDecimal value)
    {
        myCod9927 = value;
    }

    /**
     * Gets the MONTORET value of this MovCut.
     */
    public BigDecimal getMontoret()
    {
        return myMontoret;
    }

    /**
     * Sets the MONTORET value of this MovCut.
     */
    public void setMontoret(BigDecimal value)
    {
        myMontoret = value;
    }

    /**
     * Gets the MONTOIMP value of this MovCut.
     */
    public BigDecimal getMontoimp()
    {
        return myMontoimp;
    }

    /**
     * Sets the MONTOIMP value of this MovCut.
     */
    public void setMontoimp(BigDecimal value)
    {
        myMontoimp = value;
    }

    /**
     * Gets the MONTOPAG value of this MovCut.
     */
    public BigDecimal getMontopag()
    {
        return myMontopag;
    }

    /**
     * Sets the MONTOPAG value of this MovCut.
     */
    public void setMontopag(BigDecimal value)
    {
        myMontopag = value;
    }

    /**
     * Gets the PERIODOCONT value of this MovCut.
     */
    public Date getPeriodocont()
    {
        return myPeriodocont;
    }

    /**
     * Sets the PERIODOCONT value of this MovCut.
     */
    public void setPeriodocont(Date value)
    {
        myPeriodocont = value;
    }
}
