/*
 * File: MyfunctionResult.java  2008/10/09 10:09:45
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:qyP7lLS1RnPH7DmDsq6k67>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Output parameters of procedure "PKG_SII_RENTA_ME.MYFUNCTION".
 */
public class MyfunctionResult implements Serializable
{
    private static final long serialVersionUID = 1L;
    private BigDecimal myReturnValue;
    private ProcedureTable[] myTables;

    /**
     * Constructor.
     */
    public MyfunctionResult()
    {
    }

    /**
     * Returns the value of "ReturnValue".
     */
    public BigDecimal getReturnValue()
    {
        return myReturnValue;
    }

    /**
     * Changes the value of "ReturnValue".
     */
    public void setReturnValue(BigDecimal value)
    {
        myReturnValue = value;
    }

    /**
     * Returns the value of "ProcedureTables".
     */
    public ProcedureTable[] getProcedureTables()
    {
        return myTables;
    }

    /**
     * Changes the value of "ProcedureTables".
     */
    public void setProcedureTables(ProcedureTable[] value)
    {
        myTables = value;
    }
}
