/*
 * File: ProcedureTable.java  2008/10/09 10:09:46
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:brfC5Z7IdCq5ea-CsekjFm>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.io.Serializable;

/**
 * Contains the data returned in a ResultSet.
 */
public class ProcedureTable implements Serializable
{
    private static final long serialVersionUID = 1L;
    private String[] myCols;
    private Object[][] myRows;

    /**
     * Constructor.
     */
    public ProcedureTable()
    {
    }

    /**
     * Gets the column names of this ProcedureTable.
     */
    public String[] getCols()
    {
        return myCols;
    }

    /**
     * Sets the column names of this ProcedureTable.
     */
    public void setCols(String[] value)
    {
        myCols = value;
    }

    /**
     * Gets the rows of this ProcedureTable.
     */
    public Object[][] getRows()
    {
        return myRows;
    }

    /**
     * Sets the rows of this ProcedureTable.
     */
    public void setRows(Object[][] value)
    {
        myRows = value;
    }
}
