/*
 * File: SpBuscaridmonedabynemoResult.java  2008/10/09 10:09:45
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:7GUD7BAxaouO6tLjTYsNAC>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Output parameters of procedure "PKG_SII_RENTA_ME.SP_BUSCARIDMONEDABYNEMO".
 */
public class SpBuscaridmonedabynemoResult implements Serializable
{
    private static final long serialVersionUID = 1L;
    private BigDecimal myIdmoneda;
    private ProcedureTable[] myTables;

    /**
     * Constructor.
     */
    public SpBuscaridmonedabynemoResult()
    {
    }

    /**
     * Returns the value of "Idmoneda".
     */
    public BigDecimal getIdmoneda()
    {
        return myIdmoneda;
    }

    /**
     * Changes the value of "Idmoneda".
     */
    public void setIdmoneda(BigDecimal value)
    {
        myIdmoneda = value;
    }

    /**
     * Returns the value of "ProcedureTables".
     */
    public ProcedureTable[] getProcedureTables()
    {
        return myTables;
    }

    /**
     * Changes the value of "ProcedureTables".
     */
    public void setProcedureTables(ProcedureTable[] value)
    {
        myTables = value;
    }
}
