/*
 * File: SpBuscarcontitembyidmovResult.java  2008/10/09 10:09:45
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:AdOa5EBc+2CZ-SeehPlV9S>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.io.Serializable;

/**
 * Output parameters of procedure "PKG_SII_RENTA_ME.SP_BUSCARCONTITEMBYIDMOV".
 */
public class SpBuscarcontitembyidmovResult implements Serializable
{
    private static final long serialVersionUID = 1L;
    private String myCont82;
    private ProcedureTable[] myTables;

    /**
     * Constructor.
     */
    public SpBuscarcontitembyidmovResult()
    {
    }

    /**
     * Returns the value of "Cont82".
     */
    public String getCont82()
    {
        return myCont82;
    }

    /**
     * Changes the value of "Cont82".
     */
    public void setCont82(String value)
    {
        myCont82 = value;
    }

    /**
     * Returns the value of "ProcedureTables".
     */
    public ProcedureTable[] getProcedureTables()
    {
        return myTables;
    }

    /**
     * Changes the value of "ProcedureTables".
     */
    public void setProcedureTables(ProcedureTable[] value)
    {
        myTables = value;
    }
}
