/*
 * File: SpBuscaridcuentacutbyformCaller.java  2008/10/09 10:09:45
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:gelKcEyLEyDgGQU07q47N8>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;

/**
 * Implements a caller of procedure "PKG_SII_RENTA_ME.SP_BUSCARIDCUENTACUTBYFORM".
 */
public class SpBuscaridcuentacutbyformCaller extends ProcedureCaller
{
    /**
     * Executes procedure "PKG_SII_RENTA_ME.SP_BUSCARIDCUENTACUTBYFORM".
     *
     * RUT                NUMBER             Input
     * DV                 CHAR(2000)         Input
     * FORMTIPO           NUMBER             Input
     * FOLIO              NUMBER             Input
     * FECHVTO            DATE               Input
     * IDCTA              NUMBER             Output
     */
    public static SpBuscaridcuentacutbyformResult execute(Connection conn, BigDecimal rut, String dv, BigDecimal formtipo, BigDecimal folio, Date fechvto)
        throws java.sql.SQLException
    {
        SpBuscaridcuentacutbyformResult result = new SpBuscaridcuentacutbyformResult();
        ArrayList resultSets = new ArrayList();
        CallableStatement call = conn.prepareCall("{call SII.PKG_SII_RENTA_ME.SP_BUSCARIDCUENTACUTBYFORM(?,?,?,?,?,?)}");
        try
        {
            call.setBigDecimal(1, rut);
            call.setString(2, dv);
            call.setBigDecimal(3, formtipo);
            call.setBigDecimal(4, folio);
            call.setTimestamp(5, toTimestamp(fechvto));
            call.registerOutParameter(6, Types.NUMERIC);
            int updateCount = 0;
            boolean haveRset = call.execute();
            while (haveRset || updateCount != -1)
            {
                if (!haveRset)
                    updateCount = call.getUpdateCount();
                else
                    resultSets.add(toProcedureTable(call.getResultSet()));
                haveRset = call.getMoreResults();
            }
            result.setIdcta(call.getBigDecimal(6));
        }
        finally
        {
            call.close();
        }
        if (resultSets.size() > 0)
        {
            ProcedureTable[] tables = new ProcedureTable[resultSets.size()];
            result.setProcedureTables((ProcedureTable[]) resultSets.toArray(tables));
        }
        return result;
    }
}
