/*
 * File: SpBuscaridcuentacutbyformResult.java  2008/10/09 10:09:45
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:PNBJDItceyIUDpedp84KZJ>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Output parameters of procedure "PKG_SII_RENTA_ME.SP_BUSCARIDCUENTACUTBYFORM".
 */
public class SpBuscaridcuentacutbyformResult implements Serializable
{
    private static final long serialVersionUID = 1L;
    private BigDecimal myIdcta;
    private ProcedureTable[] myTables;

    /**
     * Constructor.
     */
    public SpBuscaridcuentacutbyformResult()
    {
    }

    /**
     * Returns the value of "Idcta".
     */
    public BigDecimal getIdcta()
    {
        return myIdcta;
    }

    /**
     * Changes the value of "Idcta".
     */
    public void setIdcta(BigDecimal value)
    {
        myIdcta = value;
    }

    /**
     * Returns the value of "ProcedureTables".
     */
    public ProcedureTable[] getProcedureTables()
    {
        return myTables;
    }

    /**
     * Changes the value of "ProcedureTables".
     */
    public void setProcedureTables(ProcedureTable[] value)
    {
        myTables = value;
    }
}
