/*
 * File: SpBuscarcodigoobbymovResult.java  2008/10/09 10:09:45
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:aiz9zIN71wBI4RIe7dmoib>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.io.Serializable;

/**
 * Output parameters of procedure "PKG_SII_RENTA_ME.SP_BUSCARCODIGOOBBYMOV".
 */
public class SpBuscarcodigoobbymovResult implements Serializable
{
    private static final long serialVersionUID = 1L;
    private String myResp03;
    private String myResp07;
    private String myResp87;
    private String myResp91;
    private String myResp315;
    private ProcedureTable[] myTables;

    /**
     * Constructor.
     */
    public SpBuscarcodigoobbymovResult()
    {
    }

    /**
     * Returns the value of "Resp03".
     */
    public String getResp03()
    {
        return myResp03;
    }

    /**
     * Changes the value of "Resp03".
     */
    public void setResp03(String value)
    {
        myResp03 = value;
    }

    /**
     * Returns the value of "Resp07".
     */
    public String getResp07()
    {
        return myResp07;
    }

    /**
     * Changes the value of "Resp07".
     */
    public void setResp07(String value)
    {
        myResp07 = value;
    }

    /**
     * Returns the value of "Resp87".
     */
    public String getResp87()
    {
        return myResp87;
    }

    /**
     * Changes the value of "Resp87".
     */
    public void setResp87(String value)
    {
        myResp87 = value;
    }

    /**
     * Returns the value of "Resp91".
     */
    public String getResp91()
    {
        return myResp91;
    }

    /**
     * Changes the value of "Resp91".
     */
    public void setResp91(String value)
    {
        myResp91 = value;
    }

    /**
     * Returns the value of "Resp315".
     */
    public String getResp315()
    {
        return myResp315;
    }

    /**
     * Changes the value of "Resp315".
     */
    public void setResp315(String value)
    {
        myResp315 = value;
    }

    /**
     * Returns the value of "ProcedureTables".
     */
    public ProcedureTable[] getProcedureTables()
    {
        return myTables;
    }

    /**
     * Changes the value of "ProcedureTables".
     */
    public void setProcedureTables(ProcedureTable[] value)
    {
        myTables = value;
    }
}
