/*
 * File: SpExisteRegistradoFormmovtoResult.java  2008/10/09 10:09:45
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:Lc7-wxnkl6lU74UlGFEAg3>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Output parameters of procedure "PKG_SII_RENTA_ME.SP_EXISTE_REGISTRADO_FORMMOVTO".
 */
public class SpExisteRegistradoFormmovtoResult implements Serializable
{
    private static final long serialVersionUID = 1L;
    private BigDecimal myIndexiste;
    private BigDecimal myRutout;
    private String myDvout;
    private BigDecimal myFormtipoout;
    private BigDecimal myFolioout;
    private ProcedureTable[] myTables;

    /**
     * Constructor.
     */
    public SpExisteRegistradoFormmovtoResult()
    {
    }

    /**
     * Returns the value of "Indexiste".
     */
    public BigDecimal getIndexiste()
    {
        return myIndexiste;
    }

    /**
     * Changes the value of "Indexiste".
     */
    public void setIndexiste(BigDecimal value)
    {
        myIndexiste = value;
    }

    /**
     * Returns the value of "Rutout".
     */
    public BigDecimal getRutout()
    {
        return myRutout;
    }

    /**
     * Changes the value of "Rutout".
     */
    public void setRutout(BigDecimal value)
    {
        myRutout = value;
    }

    /**
     * Returns the value of "Dvout".
     */
    public String getDvout()
    {
        return myDvout;
    }

    /**
     * Changes the value of "Dvout".
     */
    public void setDvout(String value)
    {
        myDvout = value;
    }

    /**
     * Returns the value of "Formtipoout".
     */
    public BigDecimal getFormtipoout()
    {
        return myFormtipoout;
    }

    /**
     * Changes the value of "Formtipoout".
     */
    public void setFormtipoout(BigDecimal value)
    {
        myFormtipoout = value;
    }

    /**
     * Returns the value of "Folioout".
     */
    public BigDecimal getFolioout()
    {
        return myFolioout;
    }

    /**
     * Changes the value of "Folioout".
     */
    public void setFolioout(BigDecimal value)
    {
        myFolioout = value;
    }

    /**
     * Returns the value of "ProcedureTables".
     */
    public ProcedureTable[] getProcedureTables()
    {
        return myTables;
    }

    /**
     * Changes the value of "ProcedureTables".
     */
    public void setProcedureTables(ProcedureTable[] value)
    {
        myTables = value;
    }
}
