/*
 * File: SpFindMsgmovByLlaveResult.java  2008/10/09 10:09:45
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:ylx54hsn3w3YgvEoa8tD2a>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Output parameters of procedure "PKG_SII_RENTA_ME.SP_FIND_MSGMOV_BY_LLAVE".
 */
public class SpFindMsgmovByLlaveResult implements Serializable
{
    private static final long serialVersionUID = 1L;
    private BigDecimal myExisteout;
    private String myMsjout;
    private String myValorOut;
    private ProcedureTable[] myTables;

    /**
     * Constructor.
     */
    public SpFindMsgmovByLlaveResult()
    {
    }

    /**
     * Returns the value of "Existeout".
     */
    public BigDecimal getExisteout()
    {
        return myExisteout;
    }

    /**
     * Changes the value of "Existeout".
     */
    public void setExisteout(BigDecimal value)
    {
        myExisteout = value;
    }

    /**
     * Returns the value of "Msjout".
     */
    public String getMsjout()
    {
        return myMsjout;
    }

    /**
     * Changes the value of "Msjout".
     */
    public void setMsjout(String value)
    {
        myMsjout = value;
    }

    /**
     * Returns the value of "ValorOut".
     */
    public String getValorOut()
    {
        return myValorOut;
    }

    /**
     * Changes the value of "ValorOut".
     */
    public void setValorOut(String value)
    {
        myValorOut = value;
    }

    /**
     * Returns the value of "ProcedureTables".
     */
    public ProcedureTable[] getProcedureTables()
    {
        return myTables;
    }

    /**
     * Changes the value of "ProcedureTables".
     */
    public void setProcedureTables(ProcedureTable[] value)
    {
        myTables = value;
    }
}
