/*
 * File: SpGenerarfolio01meResult.java  2008/10/09 10:09:45
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:BkdDasLrofEYtT22uTU0m9>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Output parameters of procedure "PKG_SII_RENTA_ME.SP_GENERARFOLIO01ME".
 */
public class SpGenerarfolio01meResult implements Serializable
{
    private static final long serialVersionUID = 1L;
    private BigDecimal myFol01out;
    private ProcedureTable[] myTables;

    /**
     * Constructor.
     */
    public SpGenerarfolio01meResult()
    {
    }

    /**
     * Returns the value of "Fol01out".
     */
    public BigDecimal getFol01out()
    {
        return myFol01out;
    }

    /**
     * Changes the value of "Fol01out".
     */
    public void setFol01out(BigDecimal value)
    {
        myFol01out = value;
    }

    /**
     * Returns the value of "ProcedureTables".
     */
    public ProcedureTable[] getProcedureTables()
    {
        return myTables;
    }

    /**
     * Changes the value of "ProcedureTables".
     */
    public void setProcedureTables(ProcedureTable[] value)
    {
        myTables = value;
    }
}
