/*
 * File: SpInsertMsgRentaMeCaller.java  2008/10/09 10:09:45
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:Bm+5xUQyWB4sw6WXBgc3Dz>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;

/**
 * Implements a caller of procedure "PKG_SII_RENTA_ME.SP_INSERT_MSG_RENTA_ME".
 */
public class SpInsertMsgRentaMeCaller extends ProcedureCaller
{
    /**
     * Executes procedure "PKG_SII_RENTA_ME.SP_INSERT_MSG_RENTA_ME".
     *
     * MESSAGEID          VARCHAR2(4000)     Input
     * CODE               VARCHAR2(4000)     Input
     * FECHAIN            DATE               Input
     * IDENTIF            NUMBER             Input
     * RUTCONTR           NUMBER             Input
     * FORMULARIO         NUMBER             Input
     * FOLIODECL          NUMBER             Input
     * PERIODOCONT        NUMBER             Input
     * STATUS             CHAR(2000)         Input
     * XML                CLOB               Input
     * FECHA9927          NUMBER             Input
     * RESPOUT            NUMBER             Output
     */
    public static SpInsertMsgRentaMeResult execute(Connection conn, String messageid, String code, Date fechain, BigDecimal identif, BigDecimal rutcontr, BigDecimal formulario, BigDecimal foliodecl, BigDecimal periodocont, String status, String xml, BigDecimal fecha9927)
        throws java.sql.SQLException
    {
        SpInsertMsgRentaMeResult result = new SpInsertMsgRentaMeResult();
        ArrayList resultSets = new ArrayList();
        CallableStatement call = conn.prepareCall("{call SII.PKG_SII_RENTA_ME.SP_INSERT_MSG_RENTA_ME(?,?,?,?,?,?,?,?,?,?,?,?)}");
        try
        {
            call.setString(1, messageid);
            call.setString(2, code);
            call.setTimestamp(3, toTimestamp(fechain));
            call.setBigDecimal(4, identif);
            call.setBigDecimal(5, rutcontr);
            call.setBigDecimal(6, formulario);
            call.setBigDecimal(7, foliodecl);
            call.setBigDecimal(8, periodocont);
            call.setString(9, status);
            call.setClob(10, toClob(xml, conn));
            call.setBigDecimal(11, fecha9927);
            call.registerOutParameter(12, Types.NUMERIC);
            int updateCount = 0;
            boolean haveRset = call.execute();
            while (haveRset || updateCount != -1)
            {
                if (!haveRset)
                    updateCount = call.getUpdateCount();
                else
                    resultSets.add(toProcedureTable(call.getResultSet()));
                haveRset = call.getMoreResults();
            }
            result.setRespout(call.getBigDecimal(12));
        }
        finally
        {
            call.close();
        }
        if (resultSets.size() > 0)
        {
            ProcedureTable[] tables = new ProcedureTable[resultSets.size()];
            result.setProcedureTables((ProcedureTable[]) resultSets.toArray(tables));
        }
        return result;
    }
}
