/*
 * File: SpInsertMsgRentaMeResult.java  2008/10/09 10:09:45
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:MdAfv8LyptYEOaY3FPNeYe>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Output parameters of procedure "PKG_SII_RENTA_ME.SP_INSERT_MSG_RENTA_ME".
 */
public class SpInsertMsgRentaMeResult implements Serializable
{
    private static final long serialVersionUID = 1L;
    private BigDecimal myRespout;
    private ProcedureTable[] myTables;

    /**
     * Constructor.
     */
    public SpInsertMsgRentaMeResult()
    {
    }

    /**
     * Returns the value of "Respout".
     */
    public BigDecimal getRespout()
    {
        return myRespout;
    }

    /**
     * Changes the value of "Respout".
     */
    public void setRespout(BigDecimal value)
    {
        myRespout = value;
    }

    /**
     * Returns the value of "ProcedureTables".
     */
    public ProcedureTable[] getProcedureTables()
    {
        return myTables;
    }

    /**
     * Changes the value of "ProcedureTables".
     */
    public void setProcedureTables(ProcedureTable[] value)
    {
        myTables = value;
    }
}
