/*
 * File: SpRegistraCuentaCutCaller.java  2008/10/09 10:09:45
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:TCnHpYvKtqoGTXLQwprgpa>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;

/**
 * Implements a caller of procedure "PKG_SII_RENTA_ME.SP_REGISTRA_CUENTA_CUT".
 */
public class SpRegistraCuentaCutCaller extends ProcedureCaller
{
    /**
     * Executes procedure "PKG_SII_RENTA_ME.SP_REGISTRA_CUENTA_CUT".
     *
     * RUT                NUMBER             Input
     * DV                 CHAR(2000)         Input
     * FORMTIPO           NUMBER             Input
     * FOLIO              NUMBER             Input
     * INSTIT             NUMBER             Input
     * PERIODO            DATE               Input
     * FECHA_CREA         DATE               Input
     * FECHA_ACT          DATE               Input
     * FECHA_VTO          DATE               Input
     * MONEDA             NUMBER             Input
     * SALDO              NUMBER             Input
     * RECTI              VARCHAR2(4000)     Input
     * IDOUT              NUMBER             Output
     */
    public static SpRegistraCuentaCutResult execute(Connection conn, BigDecimal rut, String dv, BigDecimal formtipo, BigDecimal folio, BigDecimal instit, Date periodo, Date fechaCrea, Date fechaAct, Date fechaVto, BigDecimal moneda, BigDecimal saldo, String recti)
        throws java.sql.SQLException
    {
        SpRegistraCuentaCutResult result = new SpRegistraCuentaCutResult();
        ArrayList resultSets = new ArrayList();
        CallableStatement call = conn.prepareCall("{call SII.PKG_SII_RENTA_ME.SP_REGISTRA_CUENTA_CUT(?,?,?,?,?,?,?,?,?,?,?,?,?)}");
        try
        {
            call.setBigDecimal(1, rut);
            call.setString(2, dv);
            call.setBigDecimal(3, formtipo);
            call.setBigDecimal(4, folio);
            call.setBigDecimal(5, instit);
            call.setTimestamp(6, toTimestamp(periodo));
            call.setTimestamp(7, toTimestamp(fechaCrea));
            call.setTimestamp(8, toTimestamp(fechaAct));
            call.setTimestamp(9, toTimestamp(fechaVto));
            call.setBigDecimal(10, moneda);
            call.setBigDecimal(11, saldo);
            call.setString(12, recti);
            call.registerOutParameter(13, Types.NUMERIC);
            int updateCount = 0;
            boolean haveRset = call.execute();
            while (haveRset || updateCount != -1)
            {
                if (!haveRset)
                    updateCount = call.getUpdateCount();
                else
                    resultSets.add(toProcedureTable(call.getResultSet()));
                haveRset = call.getMoreResults();
            }
            result.setIdout(call.getBigDecimal(13));
        }
        finally
        {
            call.close();
        }
        if (resultSets.size() > 0)
        {
            ProcedureTable[] tables = new ProcedureTable[resultSets.size()];
            result.setProcedureTables((ProcedureTable[]) resultSets.toArray(tables));
        }
        return result;
    }
}
