/*
 * File: SpGenerarfolio01meCaller.java  2008/10/09 10:09:45
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.239.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:tQBTi-H3ZAScqwMEQMOqWv>>.
 */

package cl.tesoreria.renta.me.pkgsiirentame;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Types;
import java.util.ArrayList;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "PKG_SII_RENTA_ME.buscar_cut_items".
 */
public class ValidaNumberCaller extends ProcedureCaller
{
    /**
     * Executes procedure "PKG_SII_RENTA_ME.validaNumber ".
     *
     * identificacion_in IN number
     * rut_in IN Number
     * folio_in IN Number
     * formulario_in IN Number
     * retorno_out OUT Number
     */
    public static BigDecimal execute(Connection conn, 
                                     BigDecimal numberXML,
                                     BigDecimal rut,
                                     BigDecimal folio,
                                     BigDecimal formulario) throws java.sql.SQLException
    {
        BigDecimal retorno = null;
        CallableStatement call = conn.prepareCall("{call SII.PKG_SII_RENTA_ME.validaNumber(?,?,?,?,?)}");
        try
        {
            call.setBigDecimal(1, numberXML);
            call.setBigDecimal(2, rut);
            call.setBigDecimal(3, folio);
            call.setBigDecimal(4, formulario);
            call.registerOutParameter(5, Types.NUMERIC);
            call.execute();
            retorno = (BigDecimal) call.getObject(5);
        }
        finally
        {
            call.close();
        }
        return retorno;
    }
}
