/*
 * File: AdfprocedureException.java  2008/05/09 10:54:31
 * User: Italo Maragliano Gonzalez (Tesoreria General de la Republica)
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.228.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:5mTf6msh2+cATaMmgw0Gsr>>.
 */

package cl.tesoreria.adf.adfprocedure;

/**
 * Exception thrown when the execution of a procedure fails.
 */
public class AdfprocedureException extends Exception
{
    private static final long serialVersionUID = 1L;

    /**
     * Create a new AdfprocedureException.
     */
    public AdfprocedureException()
    {
        super();
    }

    /**
     * Create a new AdfprocedureException with supplied message.
     */
    public AdfprocedureException(String message)
    {
        super(message);
    }

    /**
     * Create a new AdfprocedureException with supplied cause.
     */
    public AdfprocedureException(Throwable cause)
    {
        super(cause);
    }

    /**
     * Create a new AdfprocedureException with supplied message and cause.
     */
    public AdfprocedureException(String message, Throwable cause)
    {
        super(message, cause);
    }
}
