apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: monex-renta-moneda-extranjera-deployment
spec:
  selector:
    matchLabels:
      app: monex-renta-moneda-extranjera-app
  replicas: 2 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: monex-renta-moneda-extranjera-app
    spec:
      containers:
      - name: monex-renta-moneda-extranjera-app
        image: 604753321405.dkr.ecr.us-east-1.amazonaws.com/monex-renta-moneda-extranjera:2.0.0.0
        ports:
        - containerPort: 8088
          name: api
      imagePullSecrets:
        - name: aws-monex-registry